version: '3.9'

services:
  db:
    image: postgres:15
    container_name: desafio-db
    restart: always
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: loomi
      POSTGRES_DB: fastapi_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile
    container_name: desafio-app
    restart: always
    environment:
      DATABASE_URL: postgresql://fastapi:loomi@db:5432/fastapi_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
