name: CI/CD - Deploy EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  EKS_CLUSTER: ${{ secrets.EKS_CLUSTER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Login na AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login no ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build e Push da imagem
      run: |
        docker build -t $ECR_REPOSITORY:latest -f app/docker/Dockerfile app
        docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:latest


    - name: Atualizar kubeconfig
      run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

    - name: Aplicar deploy no EKS
      run: kubectl apply -f k8s/desafio-app-deployment.yaml
